from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import GroupShuffleSplit, train_test_split

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from data_utils import ensure_parent, load_config
from features import feature_column_names
from modeling import build_binary_classifier, compile_binary_classifier
from scaler_utils import apply_standard_scaler, fit_standard_scaler, save_scaler_json, write_scaler_header


def split_dataframe(df: pd.DataFrame, config: dict) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    seed = int(config["training"]["random_seed"])
    validation_split = float(config["training"]["validation_split"])
    test_split = float(config["training"]["test_split"])
    temp_split = validation_split + test_split

    if "session_id" in df.columns and df["session_id"].notna().any():
        groups = df["session_id"].fillna("missing_session")
        splitter = GroupShuffleSplit(n_splits=1, test_size=temp_split, random_state=seed)
        train_idx, temp_idx = next(splitter.split(df, groups=groups))
        train_df = df.iloc[train_idx].copy()
        temp_df = df.iloc[temp_idx].copy()

        relative_test_split = test_split / temp_split
        temp_groups = temp_df["session_id"].fillna("missing_session")
        second_splitter = GroupShuffleSplit(n_splits=1, test_size=relative_test_split, random_state=seed + 1)
        val_idx, test_idx = next(second_splitter.split(temp_df, groups=temp_groups))
        val_df = temp_df.iloc[val_idx].copy()
        test_df = temp_df.iloc[test_idx].copy()
        return train_df, val_df, test_df

    train_df, temp_df = train_test_split(
        df,
        test_size=temp_split,
        random_state=seed,
        stratify=df["label"],
    )
    relative_test_split = test_split / temp_split
    val_df, test_df = train_test_split(
        temp_df,
        test_size=relative_test_split,
        random_state=seed + 1,
        stratify=temp_df["label"],
    )
    return train_df.copy(), val_df.copy(), test_df.copy()


def encode_binary_labels(series: pd.Series, positive_label: str = "leak") -> np.ndarray:
    return (series == positive_label).astype(np.float32).to_numpy()


def save_json(data: dict, output_path: Path) -> None:
    ensure_parent(output_path)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2)


def compute_binary_metrics(y_true: np.ndarray, y_prob: np.ndarray, threshold: float) -> dict[str, float]:
    y_pred = (y_prob >= threshold).astype(np.int32)
    metrics = {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    }
    if len(np.unique(y_true)) > 1:
        metrics["roc_auc"] = float(roc_auc_score(y_true, y_prob))
    return metrics


def main() -> None:
    parser = argparse.ArgumentParser(description="Train the binary leak model used by the ESP32 Arduino firmware.")
    parser.add_argument(
        "--config",
        type=Path,
        default=ROOT / "configs" / "experiment.json",
        help="Path to experiment configuration.",
    )
    parser.add_argument(
        "--features",
        type=Path,
        default=ROOT / "data" / "features" / "features.csv",
        help="Feature CSV generated by extract_features.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "models",
        help="Directory for model artifacts.",
    )
    parser.add_argument(
        "--firmware-dir",
        type=Path,
        default=ROOT / "exports" / "firmware_model",
        help="Directory for firmware-side scaler export.",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    feature_names = feature_column_names(config)
    threshold = float(config["deployment"]["decision_threshold"])
    df = pd.read_csv(args.features)
    df = df[df["label"].isin(config["target_labels"])].reset_index(drop=True)

    train_df, val_df, test_df = split_dataframe(df, config)

    x_train = train_df[feature_names].fillna(0.0).to_numpy(dtype=np.float32)
    x_val = val_df[feature_names].fillna(0.0).to_numpy(dtype=np.float32)
    x_test = test_df[feature_names].fillna(0.0).to_numpy(dtype=np.float32)

    y_train = encode_binary_labels(train_df["label"])
    y_val = encode_binary_labels(val_df["label"])
    y_test = encode_binary_labels(test_df["label"])

    means, stds = fit_standard_scaler(x_train)
    x_train_scaled = apply_standard_scaler(x_train, means, stds)
    x_val_scaled = apply_standard_scaler(x_val, means, stds)
    x_test_scaled = apply_standard_scaler(x_test, means, stds)

    tf.keras.utils.set_random_seed(int(config["training"]["random_seed"]))
    model = build_binary_classifier(config, input_dim=x_train_scaled.shape[1])
    compile_binary_classifier(model, config)

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=6,
            restore_best_weights=True,
        )
    ]

    history = model.fit(
        x=x_train_scaled,
        y=y_train,
        validation_data=(x_val_scaled, y_val),
        epochs=int(config["training"]["epochs"]),
        batch_size=int(config["training"]["batch_size"]),
        callbacks=callbacks,
        verbose=2,
    )

    val_prob = model.predict(x_val_scaled, verbose=0).reshape(-1)
    test_prob = model.predict(x_test_scaled, verbose=0).reshape(-1)

    metrics = {
        "decision_threshold": threshold,
        "validation": compute_binary_metrics(y_val, val_prob, threshold),
        "test": compute_binary_metrics(y_test, test_prob, threshold),
        "train_size": int(len(train_df)),
        "validation_size": int(len(val_df)),
        "test_size": int(len(test_df)),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    model_path = args.output_dir / "leak_binary_classifier.keras"
    history_path = args.output_dir / "history.csv"
    metrics_path = args.output_dir / "metrics.json"
    feature_names_path = args.output_dir / "feature_columns.json"
    label_map_path = args.output_dir / "label_map.json"
    scaler_json_path = args.output_dir / "scaler_params.json"
    scaler_header_path = args.firmware_dir / "scaler_params.h"

    model.save(model_path)
    pd.DataFrame(history.history).to_csv(history_path, index=False)
    train_df.to_csv(args.output_dir / "train_set.csv", index=False)
    val_df.to_csv(args.output_dir / "validation_set.csv", index=False)
    test_df.to_csv(args.output_dir / "test_set.csv", index=False)
    save_json(metrics, metrics_path)
    save_json({"feature_columns": feature_names}, feature_names_path)
    save_json({"labels": config["target_labels"]}, label_map_path)
    save_scaler_json(feature_names, means, stds, scaler_json_path)
    write_scaler_header(feature_names, means, stds, scaler_header_path)

    print(f"Saved model to {model_path}")
    print(f"Saved scaler header to {scaler_header_path}")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
